In [2]:
import numpy as np

In [3]:
# create a 1-dimensional array
a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


In [5]:
# create a 2-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [6]:
# create an array of zeros
c = np.zeros((3, 4))
print(c)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# create an array of ones
d = np.ones((2, 2))
print(d)


[[1. 1.]
 [1. 1.]]


In [8]:
# add two arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=a+b
print(c)

[5 7 9]


In [9]:
# multiply two arrays

d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 26], [7, 8]])
f=d*e
print (f)


[[ 5 52]
 [21 32]]


In [13]:
#perform matrix multiplication
g=np.array([[1, 2], [3, 4]])
h=np.array([[5, 6], [7, 8]])
i=np.dot(g, h)
print(i)


[[19 22]
 [43 50]]
